AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function to add context to CloudWatch Alarms
Resources:

  AlarmContextToolSNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "Alarm Context DLQ"
      TopicName: "AlarmContextToolDLQ"
      KmsMasterKeyId: alias/aws/sns

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies_layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
      BuildArchitecture: x86_64

  AlarmContextFunction:
    # checkov:skip=CKV_AWS_117:The Lambda function needs to access resources over the Internet
    # checkov:skip=CKV_AWS_173:Environment variables do not contain sensitive data
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Wildcards are required for permissions to apply read permissions to any resource"
          - id: W89
            reason: "The Lambda function needs to access resources over the Internet"     
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alarm_context_tool
      DeadLetterQueue:
        Type: SNS
        TargetArn: !GetAtt AlarmContextToolSNSTopic.TopicArn
      Description: >-
        A Lambda function to add context to CloudWatch Alarms
      MemorySize: 1024
      Timeout: 900
      Handler: lambda_function.alarm_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          AWS_LAMBDA_LOG_LEVEL: INFO
          ANTHROPIC_VERSION: bedrock-2023-05-31
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          BEDROCK_REGION: us-east-1
          BEDROCK_MAX_TOKENS: 4000
          METRIC_ROUNDING_PRECISION_FOR_BEDROCK: 3
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_LOG_EVENT: "True"
          POWERTOOLS_SERVICE_NAME: Alarm
          POWERTOOLS_TRACER_CAPTURE_RESPONSE: "False"
          RECIPIENT: aliving@amazon.com
          SENDER: Alex Livingstone <aliving@amazon.com>
          USE_BEDROCK: "True"    
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:49
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2:7
        - !Ref DependenciesLayer
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeImages
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:        
                - sns:GetTopicAttributes
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:              
                - synthetics:DescribeCanariesLastRun
                - synthetics:DescribeCanaries
                - synthetics:GetCanaryRuns
              Resource: "*" 
        - Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:DescribeLoadBalancers
                - elasticloadbalancing:DescribeTags
                - elasticloadbalancing:DescribeTargetGroups 
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:               
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:GetLogEvents
                - logs:FilterLogEvents                
                - logs:FilterLogEvents
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - lambda:GetFunction
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendRawEmail
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ecs:DescribeClusters
                - ecs:DescribeTaskDefinition
                - ecs:DescribeServices
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:DescribeInstanceInformation
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:ListTagsOfResource
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - autoscaling:DescribeAutoScalingGroups
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricWidgetImage
                - cloudwatch:GetMetricData
                - cloudwatch:DescribeAlarmHistory
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - xray:GetTraceSummaries
                - xray:BatchGetTraces
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:ListCommands
              Resource: "*" 
        - Statement:
            - Effect: Allow
              Action:    
                - health:DescribeEvents
                - health:DescribeEventDetails
              Resource: "*" 
        - Statement:
            - Effect: Allow
              Action:   
                - cloudformation:GetTemplate
              Resource: "*"  
        - Statement:
            - Effect: Allow
              Action:  
                - rds:DescribeDBClusters
                - rds:DescribeDBInstances
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - pi:ListAvailableResourceMetrics
                - pi:GetResourceMetrics
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - eks:DescribeCluster
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: arn:*:bedrock:*::foundation-model/*
        - Statement:
            - Effect: Allow
              Action: 
                - apigateway:GET
              Resource:
                - arn:aws:apigateway:*::/apis/*/stages
                - arn:aws:apigateway:*::/apis/*/stages/*                
                - arn:aws:apigateway:*::/restapis
                - arn:aws:apigateway:*::/restapis/*   
        - Statement:
            - Effect: Allow
              Action: 
                - sns:Publish
              Resource: !GetAtt AlarmContextToolSNSTopic.TopicArn
      ReservedConcurrentExecutions: 10        
      Tracing: Active
      LoggingConfig:
        LogFormat: JSON 
