AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function to add context to CloudWatch Alarms
Resources:

  AlarmContextToolKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key for encrypting Lambda environment variables
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 
              - "kms:*"
            Resource: "*"

  AlarmContextToolKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/lambda-env-vars
      TargetKeyId: !Ref AlarmContextToolKMSKey

  AlarmContextToolLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaKMSAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                  - kms:GenerateDataKeyWithoutPlaintext
                  - kms:DescribeKey
                Resource: !GetAtt AlarmContextToolKMSKey.Arn

  AlarmContextToolSNSTopic:
  
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: "Alarm Context DLQ"
      TopicName: "AlarmContextToolDLQ"
      KmsMasterKeyId: alias/aws/sns

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies_layer/
      CompatibleRuntimes:
        - python3.12
    Metadata:
      BuildMethod: python3.12
      BuildArchitecture: x86_64

  AlarmContextFunction:
    Role: !GetAtt AlarmContextToolLambdaExecutionRole.Arn

    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alarm_context_tool/
      DeadLetterQueue:
        Type: SNS
        TargetArn: !GetAtt AlarmContextToolSNSTopic.TopicArn
      Description: >-
        A Lambda function to add context to CloudWatch Alarms
      MemorySize: 1024
      Timeout: 900
      Handler: lambda_function.alarm_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          AWS_LAMBDA_LOG_LEVEL: INFO
          ANTHROPIC_VERSION: bedrock-2023-05-31
          BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
          BEDROCK_REGION: us-east-1
          BEDROCK_MAX_TOKENS: 4000
          METRIC_ROUNDING_PRECISION_FOR_BEDROCK: 3
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_LOGGER_LOG_EVENT: "True"
          POWERTOOLS_SERVICE_NAME: Alarm
          POWERTOOLS_TRACER_CAPTURE_RESPONSE: "False"
          RECIPIENT: aliving@amazon.com
          SENDER: Alex Livingstone <aliving@amazon.com>
          USE_BEDROCK: "True"    
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - arn:aws:lambda:us-east-2:580247275435:layer:LambdaInsightsExtension:49
        - arn:aws:lambda:us-east-2:017000801446:layer:AWSLambdaPowertoolsPythonV2:67
        - !Ref DependenciesLayer
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeInstances
                - ec2:DescribeImages
              Resource: "*"
            - Effect: Allow
              Action:        
                - sns:GetTopicAttributes
              Resource: "*"
            - Effect: Allow
              Action:              
                - synthetics:DescribeCanariesLastRun
                - synthetics:DescribeCanaries
                - synthetics:GetCanaryRuns
              Resource: "*" 
            - Effect: Allow
              Action:
                - elasticloadbalancing:DescribeLoadBalancers
                - elasticloadbalancing:DescribeTags
                - elasticloadbalancing:DescribeTargetGroups 
              Resource: "*"
            - Effect: Allow
              Action:               
                - logs:DescribeLogGroups
                - logs:DescribeLogStreams
                - logs:GetLogEvents
                - logs:FilterLogEvents                
                - logs:FilterLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - lambda:GetFunction
              Resource: "*"
            - Effect: Allow
              Action:
                - ses:SendRawEmail
              Resource: "*"
            - Effect: Allow
              Action:
                - ecs:DescribeClusters
                - ecs:DescribeTaskDefinition
                - ecs:DescribeServices
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:DescribeInstanceInformation
              Resource: "*"
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:ListTagsOfResource
              Resource: "*"
            - Effect: Allow
              Action:
                - autoscaling:DescribeAutoScalingGroups
              Resource: "*"
            - Effect: Allow
              Action:
                - cloudwatch:GetMetricWidgetImage
                - cloudwatch:GetMetricData
                - cloudwatch:DescribeAlarmHistory
              Resource: "*"
            - Effect: Allow
              Action:
                - xray:GetTraceSummaries
                - xray:BatchGetTraces
              Resource: "*"
            - Effect: Allow
              Action:
                - ssm:ListCommands
              Resource: "*" 
            - Effect: Allow
              Action:    
                - health:DescribeEvents
                - health:DescribeEventDetails
              Resource: "*" 
            - Effect: Allow
              Action:   
                - cloudformation:GetTemplate
              Resource: "*"  
            - Effect: Allow
              Action:  
                - rds:DescribeDBClusters
                - rds:DescribeDBInstances
              Resource: "*"
            - Effect: Allow
              Action:
                - pi:ListAvailableResourceMetrics
                - pi:GetResourceMetrics
              Resource: "*"
            - Effect: Allow
              Action:
                - eks:DescribeCluster
              Resource: "*"
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: arn:*:bedrock:*::foundation-model/*
            - Effect: Allow
              Action: 
                - apigateway:GET
              Resource:
                - arn:aws:apigateway:*::/apis/*/stages
                - arn:aws:apigateway:*::/apis/*/stages/*                
                - arn:aws:apigateway:*::/restapis
                - arn:aws:apigateway:*::/restapis/*   
            - Effect: Allow
              Action: 
                - sns:Publish
              Resource: !GetAtt AlarmContextToolSNSTopic.TopicArn
      ReservedConcurrentExecutions: 10        
      Tracing: Active
      LoggingConfig:
        LogFormat: JSON 
